spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: file:///${user.home}/workspace/config
          cloneOnStart: false
          forcePull: false
          searchPaths: a*,b*,c*,e*,p*,s*,m*,z*
server:
  port: 8888     
  
management:
  server:
    servlet:
      context-path: /manage 
  health:
    mail:
      enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.host}:1111/eureka/
  instance:
    preferIpAddress: true
    ipAddress: ${eureka.client.host}
    leaseRenewalIntervalInSeconds: 15
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      management.context-path: /manage/
    statusPageUrlPath: /manage/info
    healthCheckUrlPath: /manage/health     
